@url = https://8080-professiona-gamessw2202-ed4r61dmxtn.ws-us116.gitpod.io

GET {{url}}/jogos

###

POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Borderlands 3",
    "plataformas": [
        {"id": 2}
    ]
}