@url = https://8080-professiona-gamessw2202-zcs1bua43sr.ws-us116.gitpod.io
GET {{url}}/jogos

###

POST {{url}}/jogos
Content-Type: application/json

{
    "titulo": "Borderlands 3",                      
    "plataformas": [
        {"id": 1},
        {"id": 2}
    ]
}

###

DELETE {{url}}/jogos/1

###

PUT {{url}}/jogos/5
Content-Type: application/json

{
    "titulo": "Borderlands 5",                      
    "plataformas": [
        {"id": 2}
    ]
}
