@url = https://8080-professiona-gamessw2202-zcs1bua43sr.ws-us116.gitpod.io
GET {{url}}/plataformas

###
POST {{url}}/plataformas
Content-Type: application/json

{
    "nome": "op"
}

###
GET {{url}}/plataformas/8